=== karanjude/snippets/database_systems/executions/hw3/conference.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/student"
	xmlns:tns="http://www.example.org/student" elementFormDefault="qualified">
	<element name="conferences" type="tns:conferences"></element>

	<complexType name="conferences">
		<sequence>
			<element name="conference" type="tns:conferenceType"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="conferenceType">
		<sequence>
			<element name="name" type="string" maxOccurs="1" minOccurs="1">
			</element>
			<element name="year" type="int" maxOccurs="1" minOccurs="1">
			</element>
			<element name="chair" type="string" maxOccurs="unbounded"
				minOccurs="1">
			</element>
			<element name="topic" type="string" maxOccurs="1" minOccurs="1">
			</element>
			<element name="city" type="string" maxOccurs="1" minOccurs="1">
			</element>
			<element name="country" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="hotelchainname" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="hotelbranchname" type="string" maxOccurs="1"
				minOccurs="1"></element>
		</sequence>
	</complexType>

</schema>

=== karanjude/snippets/database_systems/DBHomework4/src/conference.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:conferences xmlns:tns="http://www.example.org/student" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/student conference.xsd ">
  <tns:conference>
    <tns:name>tns:name</tns:name>
    <tns:year>0</tns:year>
    <tns:chair>tns:chair</tns:chair>
    <tns:topic>tns:topic</tns:topic>
    <tns:city>tns:city</tns:city>
    <tns:country>tns:country</tns:country>
    <tns:hotelchainname>tns:hotelchainname</tns:hotelchainname>
    <tns:hotelbranchname>tns:hotelbranchname</tns:hotelbranchname>
  </tns:conference>
</tns:conferences>
