=== karanjude/snippets/database_systems/DBHomework4/src/hotel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/student"
	xmlns:tns="http://www.example.org/student" elementFormDefault="qualified">
	<element name="hotels" type="tns:hotels"></element>

	<complexType name="hotels">
		<sequence>
			<element name="hotel" type="tns:hotelType" maxOccurs="unbounded"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="hotelType">
		<sequence>
			<element name="chainname" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="branchname" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="address" maxOccurs="1" minOccurs="1">
				<complexType>
					<sequence>
						<element name="city" type="string" maxOccurs="1"
							minOccurs="1"></element>
						<element name="zip" type="string" maxOccurs="1" minOccurs="1"></element>
						<element name="state" type="string" maxOccurs="1"
							minOccurs="1"></element>
						<element name="streetno" type="string" maxOccurs="1"
							minOccurs="1"></element>
						<element name="streetname" type="string" maxOccurs="1"
							minOccurs="1"></element>
					</sequence>
				</complexType>

			</element>
			<element name="capacity" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="latitude" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="longitude" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>


</schema>

=== karanjude/snippets/database_systems/DBHomework4/src/hotel.xml
<?xml version="1.0" encoding="UTF-8"?>
<hotels xmlns="http://www.example.org/student" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/student hotel.xsd ">

<hotel>
    <chainname>Hilton</chainname>
    <branchname>B1</branchname>
    <address>
      <city>Seattle</city>
      <zip>98104
</zip>
      <state>WA</state>
      <streetno>406</streetno>
      <streetname>Washington</streetname>
    </address>
    <capacity>300</capacity>
    <latitude>47.6062095</latitude>
    <longitude>-122.3078</longitude>
  </hotel>

<hotel>
    <chainname>Doubletree</chainname>
    <branchname>B2</branchname>
    <address>
      <city>Los Angeles</city>
      <zip>90007 
</zip>
      <state>CA</state>
      <streetno>132</streetno>
      <streetname>Main</streetname>
    </address>
    <capacity>900</capacity>
    <latitude>14.020137</latitude>
    <longitude>-118.29</longitude>
  </hotel>

<hotel>
    <chainname>Hilton</chainname>
    <branchname>B3</branchname>
    <address>
      <city>San Jose</city>
      <zip>95110
</zip>
      <state>CA</state>
      <streetno>300</streetno>
      <streetname>Almaden Boulevard</streetname>
    </address>
    <capacity>100</capacity>
    <latitude>37.3297849</latitude>
    <longitude>-121.8996</longitude>
  </hotel>

<hotel>
    <chainname>Hyatt</chainname>
    <branchname>B4</branchname>
    <address>
      <city>Los Angeles</city>
      <zip>90007
</zip>
      <state>CA</state>
      <streetno>148</streetno>
      <streetname>Exposition</streetname>
    </address>
    <capacity>500</capacity>
    <latitude>14.026535</latitude>
    <longitude>-118.265</longitude>
  </hotel>

<hotel>
    <chainname>Hilton</chainname>
    <branchname>B5</branchname>
    <address>
      <city>Chicago</city>
      <zip>60603
</zip>
      <state>IL</state>
      <streetno>678</streetno>
      <streetname>East Monroe Street</streetname>
    </address>
    <capacity>150</capacity>
    <latitude>30.120635</latitude>
    <longitude>-70.27</longitude>
  </hotel>

<hotel>
    <chainname>Doubletree</chainname>
    <branchname>B7</branchname>
    <address>
      <city>New York</city>
      <zip>11209
</zip>
      <state>NY</state>
      <streetno>160</streetno>
      <streetname>Main</streetname>
    </address>
    <capacity>600</capacity>
    <latitude>40.7142691</latitude>
    <longitude>-74.239</longitude>
  </hotel>

<hotel>
    <chainname>Doubletree</chainname>
    <branchname>B8</branchname>
    <address>
      <city>San Jose</city>
      <zip>95110
</zip>
      <state>CA</state>
      <streetno>2050</streetno>
      <streetname>Gateway Place</streetname>
    </address>
    <capacity>1300</capacity>
    <latitude>35.055635</latitude>
    <longitude>-120.30</longitude>
  </hotel>

<hotel>
    <chainname>Caesars</chainname>
    <branchname>B9</branchname>
    <address>
      <city>Portland</city>
      <zip>97405
</zip>
      <state>OR</state>
      <streetno>797</streetno>
      <streetname>California</streetname>
    </address>
    <capacity>900</capacity>
    <latitude>44.026535</latitude>
    <longitude>-121.265</longitude>
  </hotel>

<hotel>
    <chainname>Caesars</chainname>
    <branchname>B10</branchname>
    <address>
      <city>Seattle</city>
      <zip>98104
</zip>
      <state>WA</state>
      <streetno>314</streetno>
      <streetname>3rd</streetname>
    </address>
    <capacity>500</capacity>
    <latitude>46.120635</latitude>
    <longitude>-122.6008</longitude>
  </hotel>

<hotel>
    <chainname>Ario</chainname>
    <branchname>B11</branchname>
    <address>
      <city>New York</city>
      <zip>11209
</zip>
      <state>NY</state>
      <streetno>649</streetno>
      <streetname>3rd</streetname>
    </address>
    <capacity>130</capacity>
    <latitude>40.7142691</latitude>
    <longitude>-74.8288</longitude>
  </hotel>

<hotel>
    <chainname>Ario</chainname>
    <branchname>B12</branchname>
    <address>
      <city>Seattle</city>
      <zip>98104
</zip>
      <state>WA</state>
      <streetno>863</streetno>
      <streetname>Main</streetname>
    </address>
    <capacity>200</capacity>
    <latitude>44.020137</latitude>
    <longitude>-76.29</longitude>
  </hotel>

<hotel>
    <chainname>Carlton</chainname>
    <branchname>B13</branchname>
    <address>
      <city>Los Angeles</city>
      <zip>90089
</zip>
      <state>CA</state>
      <streetno>991</streetno>
      <streetname>Vermont</streetname>
    </address>
    <capacity>120</capacity>
    <latitude>34.055635</latitude>
    <longitude>-110.30</longitude>
  </hotel>

<hotel>
    <chainname>Carlton</chainname>
    <branchname>B14</branchname>
    <address>
      <city>San Jose</city>
      <zip>94086
</zip>
      <state>CA</state>
      <streetno>282</streetno>
      <streetname>Magnolia</streetname>
    </address>
    <capacity>100</capacity>
    <latitude>37.026535</latitude>
    <longitude>-120.265</longitude>
  </hotel>

<hotel>
    <chainname>Marriott</chainname>
    <branchname>B15</branchname>
    <address>
      <city>Los Angeles</city>
      <zip>90089
</zip>
      <state>CA</state>
      <streetno>504</streetno>
      <streetname>Adams</streetname>
    </address>
    <capacity>300</capacity>
    <latitude>17.120635</latitude>
    <longitude>-116.27</longitude>
  </hotel>

<hotel>
    <chainname>Marriott</chainname>
    <branchname>B16</branchname>
    <address>
      <city>New York</city>
      <zip>11209
</zip>
      <state>NY</state>
      <streetno>660</streetno>
      <streetname>Main</streetname>
    </address>
    <capacity>700</capacity>
    <latitude>40.542691</latitude>
    <longitude>-76.28</longitude>
  </hotel>

<hotel>
    <chainname>Hilton</chainname>
    <branchname>B17</branchname>
    <address>
      <city>New York</city>
      <zip>11209
</zip>
      <state>NY</state>
      <streetno>755</streetno>
      <streetname>Rose</streetname>
    </address>
    <capacity>500</capacity>
    <latitude>40.7142691</latitude>
    <longitude>-73.29</longitude>
  </hotel>

<hotel>
    <chainname>Hyatt</chainname>
    <branchname>B18</branchname>
    <address>
      <city>New York</city>
      <zip>11209
</zip>
      <state>NY</state>
      <streetno>998</streetno>
      <streetname>Magnolia</streetname>
    </address>
    <capacity>900</capacity>
    <latitude>41.7142691</latitude>
    <longitude>-73.30</longitude>
  </hotel>

<hotel>
    <chainname>Westin</chainname>
    <branchname>B19</branchname>
    <address>
      <city>New York</city>
      <zip>11209
</zip>
      <state>NY</state>
      <streetno>412</streetno>
      <streetname>Main</streetname>
    </address>
    <capacity>900</capacity>
    <latitude>40.142691</latitude>
    <longitude>-74.265</longitude>
  </hotel>

<hotel>
    <chainname>Best Western</chainname>
    <branchname>B20</branchname>
    <address>
      <city>Portland</city>
      <zip>97405
</zip>
      <state>OR</state>
      <streetno>819</streetno>
      <streetname>Washington</streetname>
    </address>
    <capacity>400</capacity>
    <latitude>45.120635</latitude>
    <longitude>-122.27</longitude>
  </hotel>

<hotel>
    <chainname>Doubletree</chainname>
    <branchname>B21</branchname>
    <address>
      <city>Portland</city>
      <zip>97405
</zip>
      <state>OR</state>
      <streetno>595</streetno>
      <streetname>Magnolia</streetname>
    </address>
    <capacity>80</capacity>
    <latitude>30.024547</latitude>
    <longitude>-122.288</longitude>
  </hotel>

<hotel>
    <chainname>Hilton</chainname>
    <branchname>B22</branchname>
    <address>
      <city>Portland</city>
      <zip>97405
</zip>
      <state>OR</state>
      <streetno>349</streetno>
      <streetname>Magnolia</streetname>
    </address>
    <capacity>110</capacity>
    <latitude>64.020137</latitude>
    <longitude>-108.29</longitude>
  </hotel>

<hotel>
    <chainname>Hilton</chainname>
    <branchname>B23</branchname>
    <address>
      <city>Portland</city>
      <zip>97405
</zip>
      <state>OR</state>
      <streetno>252</streetno>
      <streetname>Rose</streetname>
    </address>
    <capacity>800</capacity>
    <latitude>45.5234515</latitude>
    <longitude>-121.30</longitude>
  </hotel>

<hotel>
    <chainname>Holidays Inn</chainname>
    <branchname>B24</branchname>
    <address>
      <city>Los Angeles</city>
      <zip>90007
</zip>
      <state>CA</state>
      <streetno>980</streetno>
      <streetname>Washington</streetname>
    </address>
    <capacity>150</capacity>
    <latitude>34.024547</latitude>
    <longitude>-117.288</longitude>
  </hotel>

<hotel>
    <chainname>Holidays Inn</chainname>
    <branchname>B25</branchname>
    <address>
      <city>New York</city>
      <zip>11209
</zip>
      <state>NY</state>
      <streetno>503</streetno>
      <streetname>Magnolia</streetname>
    </address>
    <capacity>40</capacity>
    <latitude>40.691</latitude>
    <longitude>-73.29</longitude>
  </hotel>

<hotel>
    <chainname>Westbound</chainname>
    <branchname>B26</branchname>
    <address>
      <city>New York</city>
      <zip>11209
</zip>
      <state>NY</state>
      <streetno>532</streetno>
      <streetname>Ocean</streetname>
    </address>
    <capacity>100</capacity>
    <latitude>40.2691</latitude>
    <longitude>-74.09729</longitude>
  </hotel>

<hotel>
    <chainname>Westin</chainname>
    <branchname>B27</branchname>
    <address>
      <city>Seattle</city>
      <zip>98104</zip>
      <state>WA</state>
      <streetno>134</streetno>
      <streetname>Main</streetname>
    </address>
    <capacity>80</capacity>
    <latitude>47.362095</latitude>
    <longitude>-122.5708</longitude>
  </hotel>

<hotel>
    <chainname>Best Western</chainname>
    <branchname>B28</branchname>
    <address>
      <city>Los Angeles</city>
      <zip>90007
</zip>
      <state>CA</state>
      <streetno>852</streetno>
      <streetname>Main</streetname>
    </address>
    <capacity>130</capacity>
    <latitude>34.120635</latitude>
