=== karanjude/snippets/database_systems/DBHomework4/bookstore.dtd
<!ELEMENT bookstore (name,topic*)> 
 <!ELEMENT topic (name,book*)> 
 <!ELEMENT name (#PCDATA)> 
 <!ELEMENT book (title,author,price)> 
 <!ELEMENT title (#PCDATA)> 
 <!ELEMENT author (#PCDATA)> 
 <!ELEMENT price (#PCDATA)> 
 <!ATTLIST book isbn CDATA "0" >

=== karanjude/snippets/database_systems/DBHomework4/bookstore.xml
<?xml version="1.0"?> 
<!DOCTYPE bookstore SYSTEM "/home/jude/Data/study/judesnippets/database_systems/DBHomework4/bookstore.dtd"> 
<bookstore> 
 <name>Mike's Store</name> 
 <topic> 
   <name>XML</name> 
   <book isbn="2"> 
     <title>Mike's Guide To DTD's and XML Schemas</title> 
     <author>Mike Jervis</author> 
     <price>$30</price>
</book>
</topic> 
<topic> 
   <name>XML2</name> 
   <book isbn="1"> 
     <title>csci585 exam 2</title> 
     <author>Shamsian</author> 
     <price>$1</price>
</book></topic> 
</bookstore>
